services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  db_test:
    image: postgres:17
    restart: always
    volumes:
      - app-db-data-test:/var/lib/postgresql/data/pgdata_test
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata_test
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER_TEST?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB_TEST?Variable not set}
    ports:
      - "5433:5432"

  redis:
    image: redis:7.4
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.worker worker --loglevel=INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: celery -A app.worker beat --loglevel=INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - .:/app
      - celery-beat-data:/app/celerybeat-schedule

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_HOST=db

volumes:
  app-db-data:
  celery-beat-data:
  app-db-data-test:
